spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydemo?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: chao520
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/mongotest